# Generated by Django 3.0.5 on 2020-08-20 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名字')),
                ('ytid', models.CharField(max_length=32, unique=True, verbose_name='Youtube ID')),
                ('subscribe_count', models.IntegerField(default=0, verbose_name='订阅者数量')),
                ('avatar_url', models.TextField(blank=True, default='', verbose_name='头像地址')),
                ('home_url', models.TextField(blank=True, default='', verbose_name='主页地址')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytid', models.CharField(max_length=32, unique=True, verbose_name='Youtube ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='视频标题')),
                ('watch_count', models.IntegerField(default=0, verbose_name='视频观看数量')),
                ('upload_date', models.DateField(auto_now=True, verbose_name='视频上传时间')),
                ('up_count', models.IntegerField(default=0, verbose_name='顶的数量')),
                ('down_count', models.IntegerField(default=0, verbose_name='踩的数量')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数量')),
                ('url', models.TextField(blank=True, default='', null=True, verbose_name='视频地址')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yt.YoutubeAccount', unique=True, verbose_name='上传者')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_count', models.IntegerField(default=0, verbose_name='顶的数量')),
                ('crawl_time', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('comment_date_str', models.CharField(blank=True, max_length=32, null=True, verbose_name='评论时间')),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yt.YoutubeAccount', verbose_name='评论者')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yt.YoutubeVideo', verbose_name='评论视频')),
            ],
        ),
    ]
