# Generated by Django 3.0.5 on 2020-08-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeaccount',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='个人信息'),
        ),
        migrations.AddField(
            model_name='youtubeaccount',
            name='email',
            field=models.CharField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='youtubecomment',
            name='comment_content',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='评论内容'),
        ),
        migrations.AddField(
            model_name='youtubecomment',
            name='commenter_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='评论者名字'),
        ),
    ]
