# Generated by Django 3.0.5 on 2020-08-20 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0003_auto_20200820_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeaccount',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='youtubeaccount',
            name='home_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='主页地址'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yt.YoutubeAccount', verbose_name='上传者'),
        ),
    ]
