# Generated by Django 3.0.5 on 2020-09-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0005_auto_20200905_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecrawltask',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未开始'), (1, '已分解'), (2, '正在进行'), (3, '已完成'), (4, '失败')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='youtubecrawltask',
            name='target',
            field=models.TextField(blank=True, help_text='任务类型为"采集YouTube视频评论":则在该文本框中输入要采集的视频id，换行隔开</br>任务类型为"采集YouTube账号信息":则在该文本框中输入要采集的账号id，换行隔开</br>任务类型为"通过关键词采集Youtube视频":则在该文本框中输入要搜索的关键词，换行隔开</br>任务类型为"通过关键词采集Youtube视频及评论":则在该文本框中输入要搜索的关键词，换行隔开</br>', null=True, verbose_name='任务内容'),
        ),
    ]
